# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run unit tests
      - run: yarn test

      - setup_remote_docker:
          version: 19.03.13

      # run integration tests
      - run:
          name: Set up integration test environment
          command: |
            set -x
            export COMPOSE_TLS_VERSION=TLSv1_2
            docker-compose -f src/test/integration/docker-compose.yml up --build --exit-code-from gverse --abort-on-container-exit
